-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 12:26:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema duombaze
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `duombaze` ;

-- -----------------------------------------------------
-- Schema duombaze
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `duombaze` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema check
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `check` ;

-- -----------------------------------------------------
-- Schema check
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `check` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `duombaze` ;

-- -----------------------------------------------------
-- Table `duombaze`.`vartotojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`vartotojas` (
  `id_vartotojas` INT NOT NULL,
  `vart_vardas` VARCHAR(45) NULL,
  `slaptazodis` VARCHAR(45) NULL,
  `tipas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_vartotojas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`grupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`grupe` (
  `id_grupe` INT NOT NULL,
  `pavadinimas` VARCHAR(45) NULL,
  `fakultetas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`studentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`studentas` (
  `id_studentas` INT NOT NULL,
  `id_vartotojas` INT NOT NULL,
  `vardas` INT NULL,
  `pavarde` VARCHAR(45) NULL,
  `id_grupe` INT NOT NULL,
  PRIMARY KEY (`id_studentas`),
  INDEX `id_vartotojas_idx` (`id_vartotojas` ASC) VISIBLE,
  INDEX `id_grupe_idx` (`id_grupe` ASC) VISIBLE,
  CONSTRAINT `id_vartotojas_stud`
    FOREIGN KEY (`id_vartotojas`)
    REFERENCES `duombaze`.`vartotojas` (`id_vartotojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_grupe_stud`
    FOREIGN KEY (`id_grupe`)
    REFERENCES `duombaze`.`grupe` (`id_grupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`destytojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`destytojas` (
  `id_destytojas` INT NOT NULL,
  `id_vartotojas` INT NOT NULL,
  `vardas` VARCHAR(45) NULL,
  `pavarde` VARCHAR(45) NULL,
  PRIMARY KEY (`id_destytojas`),
  INDEX `id_vartotojas_idx` (`id_vartotojas` ASC) VISIBLE,
  CONSTRAINT `id_vartotojas_dest`
    FOREIGN KEY (`id_vartotojas`)
    REFERENCES `duombaze`.`vartotojas` (`id_vartotojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`dalykas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`dalykas` (
  `id_dalykas` INT NOT NULL,
  `pavadinimas` VARCHAR(45) NULL,
  `id_destytojas` INT NOT NULL,
  PRIMARY KEY (`id_dalykas`),
  INDEX `id_destytojas_idx` (`id_destytojas` ASC) VISIBLE,
  CONSTRAINT `id_destytojas_dal`
    FOREIGN KEY (`id_destytojas`)
    REFERENCES `duombaze`.`destytojas` (`id_destytojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`studento_dalykas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`studento_dalykas` (
  `id_studentas_dal` INT NOT NULL,
  `id_dalykas_dal` INT NOT NULL,
  PRIMARY KEY (`id_studentas_dal`, `id_dalykas_dal`),
  INDEX `id_dalykas_idx` (`id_dalykas_dal` ASC) VISIBLE,
  CONSTRAINT `id_studentas`
    FOREIGN KEY (`id_studentas_dal`)
    REFERENCES `duombaze`.`studentas` (`id_studentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dalykas`
    FOREIGN KEY (`id_dalykas_dal`)
    REFERENCES `duombaze`.`dalykas` (`id_dalykas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`pazymys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`pazymys` (
  `id_pazymys` INT NOT NULL,
  `id_dalykas` INT NOT NULL,
  `id_destytojas` INT NOT NULL,
  `pazymys` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pazymys`),
  INDEX `id_destytojas_idx` (`id_destytojas` ASC) VISIBLE,
  INDEX `id_dalykas_idx` (`id_dalykas` ASC) VISIBLE,
  CONSTRAINT `id_destytojas_paz`
    FOREIGN KEY (`id_destytojas`)
    REFERENCES `duombaze`.`destytojas` (`id_destytojas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dalykas_paz`
    FOREIGN KEY (`id_dalykas`)
    REFERENCES `duombaze`.`dalykas` (`id_dalykas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `duombaze`.`studento_pazymys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `duombaze`.`studento_pazymys` (
  `id_studentas` INT NOT NULL,
  `id_pazymys` INT NOT NULL,
  PRIMARY KEY (`id_studentas`, `id_pazymys`),
  INDEX `id_pazymys_idx` (`id_pazymys` ASC) VISIBLE,
  CONSTRAINT `id_studentas_paz`
    FOREIGN KEY (`id_studentas`)
    REFERENCES `duombaze`.`studentas` (`id_studentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pazymys_paz`
    FOREIGN KEY (`id_pazymys`)
    REFERENCES `duombaze`.`pazymys` (`id_pazymys`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `check` ;

-- -----------------------------------------------------
-- Table `check`.`ay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`ay` (
  `AY_ID` INT NOT NULL AUTO_INCREMENT,
  `ACADYR` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`AY_ID`),
  UNIQUE INDEX `acadyr` (`ACADYR` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`class` (
  `CLASS_ID` INT NOT NULL AUTO_INCREMENT,
  `CLASS_CODE` VARCHAR(30) NOT NULL,
  `SUBJ_ID` INT NOT NULL,
  `INST_ID` INT NOT NULL,
  `SYID` INT NOT NULL,
  `AY` VARCHAR(11) NOT NULL,
  `DAY` VARCHAR(20) NOT NULL,
  `C_TIME` VARCHAR(11) NOT NULL,
  `IDNO` INT NOT NULL,
  `ROOM` VARCHAR(30) NOT NULL DEFAULT 'NONE',
  `SECTION` VARCHAR(30) NOT NULL DEFAULT 'NONE',
  PRIMARY KEY (`CLASS_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`course` (
  `COURSE_ID` INT NOT NULL AUTO_INCREMENT,
  `COURSE_NAME` VARCHAR(30) NOT NULL,
  `COURSE_LEVEL` INT NOT NULL DEFAULT '1',
  `COURSE_MAJOR` VARCHAR(30) NOT NULL DEFAULT 'None',
  `COURSE_DESC` VARCHAR(255) NOT NULL,
  `DEPT_ID` INT NOT NULL,
  PRIMARY KEY (`COURSE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`department` (
  `DEPT_ID` INT NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` VARCHAR(30) NOT NULL,
  `DEPARTMENT_DESC` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DEPT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`grades` (
  `GRADE_ID` INT NOT NULL AUTO_INCREMENT,
  `IDNO` INT NOT NULL,
  `SUBJ_ID` INT NOT NULL,
  `INST_ID` INT NOT NULL,
  `SYID` INT NOT NULL,
  `FIRST` INT NOT NULL,
  `SECOND` INT NOT NULL,
  `THIRD` INT NOT NULL,
  `FOURTH` INT NOT NULL,
  `AVE` FLOAT NOT NULL,
  `DAY` VARCHAR(30) NOT NULL,
  `G_TIME` TIME NOT NULL,
  `ROOM` VARCHAR(30) NOT NULL,
  `REMARKS` TEXT NOT NULL,
  `COMMENT` TEXT NOT NULL,
  PRIMARY KEY (`GRADE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`instructor` (
  `INST_ID` INT NOT NULL AUTO_INCREMENT,
  `INST_FULLNAME` VARCHAR(255) NOT NULL,
  `INST_ADDRESS` VARCHAR(255) NOT NULL,
  `INST_SEX` VARCHAR(20) NOT NULL DEFAULT 'Male',
  `INST_STATUS` VARCHAR(20) NOT NULL DEFAULT 'Single',
  `SPECIALIZATION` TEXT NOT NULL,
  `INST_EMAIL` VARCHAR(255) NOT NULL,
  `EMPLOYMENT_STATUS` VARCHAR(40) NOT NULL DEFAULT 'Probationary',
  PRIMARY KEY (`INST_ID`),
  UNIQUE INDEX `INST_EMAIL` (`INST_EMAIL` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`level` (
  `YR_ID` INT NOT NULL AUTO_INCREMENT,
  `LEVEL` VARCHAR(30) NOT NULL,
  `LEVEL_DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`YR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`major` (
  `MAJOR_ID` INT NOT NULL AUTO_INCREMENT,
  `MAJOR` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`MAJOR_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`photo` (
  `PHOTO_ID` INT NOT NULL AUTO_INCREMENT,
  `FILENAME` TEXT NOT NULL,
  `TYPE` VARCHAR(30) NOT NULL,
  `SIZE` INT NOT NULL,
  `CAPTION` VARCHAR(255) NOT NULL,
  `IDNO` INT NOT NULL,
  `PRIMARY` VARCHAR(20) NOT NULL DEFAULT 'no',
  PRIMARY KEY (`PHOTO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`room` (
  `ROOM_ID` INT NOT NULL AUTO_INCREMENT,
  `ROOM_NAME` VARCHAR(30) NOT NULL,
  `ROOM_DESC` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ROOM_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`schoolyr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`schoolyr` (
  `SYID` INT NOT NULL AUTO_INCREMENT,
  `AY` VARCHAR(30) NOT NULL,
  `SEMESTER` VARCHAR(20) NOT NULL,
  `COURSE_ID` INT NOT NULL,
  `IDNO` INT NOT NULL,
  `CATEGORY` VARCHAR(30) NOT NULL DEFAULT 'ENROLLED',
  `DATE_RESERVED` DATETIME NOT NULL,
  `DATE_ENROLLED` DATETIME NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL DEFAULT 'New',
  PRIMARY KEY (`SYID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`semester` (
  `SEM_ID` INT NOT NULL AUTO_INCREMENT,
  `SEM` VARCHAR(15) NOT NULL DEFAULT 'First',
  PRIMARY KEY (`SEM_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`studentsubjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`studentsubjects` (
  `STUDSUBJ_ID` INT NOT NULL AUTO_INCREMENT,
  `IDNO` INT NOT NULL,
  `SUBJ_ID` INT NOT NULL,
  `LEVEL` INT NOT NULL,
  `SEMESTER` VARCHAR(30) NOT NULL,
  `SY` TEXT NOT NULL,
  PRIMARY KEY (`STUDSUBJ_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`subject` (
  `SUBJ_ID` INT NOT NULL AUTO_INCREMENT,
  `SUBJ_CODE` VARCHAR(30) NOT NULL,
  `SUBJ_DESCRIPTION` VARCHAR(255) NOT NULL,
  `UNIT` INT NOT NULL,
  `PRE_REQUISITE` VARCHAR(30) NOT NULL DEFAULT 'None',
  `COURSE_ID` INT NOT NULL,
  `AY` VARCHAR(30) NOT NULL,
  `SEMESTER` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`SUBJ_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 477
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`tblrequirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`tblrequirements` (
  `REQ_ID` INT NOT NULL AUTO_INCREMENT,
  `NSO` VARCHAR(5) NOT NULL DEFAULT 'no',
  `BAPTISMAL` VARCHAR(5) NOT NULL DEFAULT 'no',
  `ENTRANCE_TEST_RESULT` VARCHAR(5) NOT NULL DEFAULT 'no',
  `MARRIAGE_CONTRACT` VARCHAR(5) NOT NULL DEFAULT 'no',
  `CERTIFICATE_OF_TRANSFER` VARCHAR(5) NOT NULL DEFAULT 'no',
  `IDNO` INT NOT NULL,
  PRIMARY KEY (`REQ_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`tblstuddetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`tblstuddetails` (
  `DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
  `FATHER` VARCHAR(255) NOT NULL,
  `FATHER_OCCU` VARCHAR(255) NOT NULL,
  `MOTHER` VARCHAR(255) NOT NULL,
  `MOTHER_OCCU` VARCHAR(255) NOT NULL,
  `BOARDING` VARCHAR(5) NOT NULL DEFAULT 'no',
  `WITH_FAMILY` VARCHAR(5) NOT NULL DEFAULT 'yes',
  `GUARDIAN` VARCHAR(255) NOT NULL,
  `GUARDIAN_ADDRESS` VARCHAR(255) NOT NULL,
  `OTHER_PERSON_SUPPORT` VARCHAR(255) NOT NULL,
  `ADDRESS` TEXT NOT NULL,
  `IDNO` INT NOT NULL,
  PRIMARY KEY (`DETAIL_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`tblstudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`tblstudent` (
  `S_ID` INT NOT NULL AUTO_INCREMENT,
  `IDNO` INT NOT NULL,
  `FNAME` VARCHAR(40) NOT NULL,
  `LNAME` VARCHAR(40) NOT NULL,
  `MNAME` VARCHAR(40) NOT NULL,
  `SEX` VARCHAR(10) NOT NULL DEFAULT 'Male',
  `BDAY` DATE NOT NULL,
  `BPLACE` TEXT NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL,
  `AGE` INT NOT NULL,
  `NATIONALITY` VARCHAR(40) NOT NULL,
  `RELIGION` VARCHAR(255) NOT NULL,
  `CONTACT_NO` VARCHAR(40) NOT NULL,
  `HOME_ADD` TEXT NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`S_ID`),
  UNIQUE INDEX `IDNO` (`IDNO` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `check`.`useraccounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check`.`useraccounts` (
  `ACCOUNT_ID` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NAME` VARCHAR(255) NOT NULL,
  `ACCOUNT_USERNAME` VARCHAR(255) NOT NULL,
  `ACCOUNT_PASSWORD` TEXT NOT NULL,
  `ACCOUNT_TYPE` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`),
  UNIQUE INDEX `ACCOUNT_USERNAME` (`ACCOUNT_USERNAME` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `duombaze`.`vartotojas`
-- -----------------------------------------------------
START TRANSACTION;
USE `duombaze`;
INSERT INTO `duombaze`.`vartotojas` (`id_vartotojas`, `vart_vardas`, `slaptazodis`, `tipas`) VALUES (1, 'root', 'admin', 'Admin');
INSERT INTO `duombaze`.`vartotojas` (`id_vartotojas`, `vart_vardas`, `slaptazodis`, `tipas`) VALUES (2, 'martynas', 'marcius', 'Studentas');

COMMIT;
